### PR TITLE
allow specifying a non-browser environment by setting `window.document.type = 'synthetic'`

### PR DESCRIPTION
**Pull request by u9g**

### CODE REVIEW

**Comment by rom1504** [comment]
when does it help ?

**Comment by extremeheat** [comment]
The naming made me really confused for a bit, thinking this was apart of the DOM API. Is this for the headless mode? If so you can just check an environment flag.

**Comment by u9g** [comment]
> The naming made me really confused for a bit, thinking this was apart of the DOM API. Is this for the headless mode? If so you can just check an environment flag.

oh okay, I’ll do this, don’t know why I didn’t think of it

**Comment by rom1504** [comment]
re-open if you want it done

**Pull request closed without merging**
