### PR TITLE
Updated World Height

### PR DESCRIPTION
**Pull request by Kaden-Skinner**
Searched for 256 and changed it to 320 and y=0 to y=-64

### CODE REVIEW

**Comment by extremeheat** [comment]
The world height is not static anymore and changes with the version, so just updating some constants likely is not the proper fix

**Comment by extremeheat** [comment]
Additionally, have you checked this to work ?

**Comment by Kaden-Skinner** [comment]
> Additionally, have you checked this to work ?

Nope, I just figured that -64 is the lowest and I don't think it is practical to go beyond 320 as that is the default for newer versions...

**Comment by Kaden-Skinner** [comment]
> > Additionally, have you checked this to work ?
> 
> Nope, I just figured that -64 is the lowest and I don't think it is practical to go beyond 320 as that is the default for newer versions...

I have tested it now, and it does not make the viewer able to render below y=0.
Additionally, I there are more errors in the console. Whether these come from this pr or not is unknown.

<code>THREE.BufferGeometry.computeBoundingSphere(): Computed radius is NaN. The "position" attribute is likely to have NaN values</code>

**Comment by rom1504** [comment]
please update properly

**Pull request closed without merging**
