### PR TITLE
improve rendering

### LINKED ISSUE #20: improve first camera position / position for < 1.13 versions
https://prismarine.js.org/prismarine-viewer/

### PR DESCRIPTION
**Pull request by rom1504**
fix #20

### CODE REVIEW

**Comment by rom1504** [comment]
changed the view point but did not improve 1.8 rendering

**Comment by Karang** [comment]
We should understand why the first sent position is not the position of the bot. (It is sent at the spawn event using bot.entity.position)

**Comment by rom1504** [comment]
I agree, but I'm not sure yet this is even the problem. I'm trying to increase timeout just in case
I bet just adding the event you said "finished rendering" would solve it

**Comment by rom1504** [comment]
FYI the artifact are available for download if you click on the details link (I think github should make it clearer they are available, but that's how it works today)
there https://github.com/PrismarineJS/prismarine-viewer/pull/21/checks?check_run_id=879953927

**Comment by rom1504** [comment]
ok increasing the timeout does not solve it

**Comment by rom1504** [comment]
printing the position to validate the wrong initial position theory

**Comment by Karang** [comment]
> printing the position to validate the wrong initial position theory

look at gitter / discord :)

**Comment by rom1504** [comment]
it works, if you're ok with it, let's merge ?

**Pull request merged**
