### PR TITLE
Add 1.19.1 as a supported version

### PR DESCRIPTION
**Pull request by rtm516**

### CODE REVIEW

**Comment by rtm516** [comment]
Requires https://github.com/PrismarineJS/node-minecraft-assets/pull/22

**Comment by FDelporte** [comment]
Please extend with 1.19.2 (and 1.19.3)

**Comment by rtm516** [comment]
I can modify this repo, but don't know how to generate the assets for the minecraft-assets which node-minecraft-assets depends on

**Comment by FDelporte** [comment]
Thanks, this is new project for me, so checking in how this works and if I can contribute in any way...

**Comment by rom1504** [comment]
please do a release pr of dependent

**Comment by rtm516** [comment]
> please do a release pr of dependency

Not sure what you mean by this

**Comment by extremeheat** [comment]
It means you need to bump the npm package version in a release PR (see previous PRs). There is a workflow action that will trigger automatically publishing to npm which can then be used in prismarine-viewer/other packages.

**Comment by rom1504** [comment]
fails

**Comment by rom1504** [comment]
please re open if you want to work on it

**Pull request closed without merging**
