### PR TITLE
Fixes a few memory leaks

### LINKED ISSUE #196: Storage leaks
I'm using prismarine-web-client, and threejs objects are not getting released. I believe you have to 'dispose' of all the threejs objects (textures, materials, etc.) to get them to release the webgl data. With a big world, you can only play for a short time before the browser tab quits.

When a chunk is unloaded in the web client, it seems to be handled properly - the prismarine chunk is deleted. And that should release the underlying threejs objects, but you need to explicitly dispose of the textures, materials, etc. If you look at the heap snapshots, the storage that leaks is the system/JSArrayBufferData, which I think is the webgl system data. Everything else looks fine.

### PR DESCRIPTION
**Pull request by Pandapip1**
Fixes #196

(Needs testing)

### CODE REVIEW

**Comment by rom1504** [comment]
@Pandapip1 does it work?

**Comment by Pandapip1** [comment]
I need to check. I believe so.

**Comment by Pandapip1** [comment]
Yea I believe it works. The CI seems to have broke, so I'll just re-trigger it.

**Comment by Pandapip1** [comment]
Never mind, the CI is just broken.

**Comment by rom1504** [comment]
lgtm, merging, thanks

**Pull request merged**
