### PR TITLE
start puppeteer testing

### PR DESCRIPTION
**Pull request by rom1504**
WIP not ready to merge

### CODE REVIEW

**Comment by rom1504** [comment]
https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

**Comment by rom1504** [comment]
https://github.com/puppeteer/puppeteer/blob/main/.ci/node12/Dockerfile.linux

**Comment by rom1504** [comment]
https://itnext.io/how-to-use-gitpod-in-your-create-react-app-based-project-dd4d0b33ce77

**Comment by rom1504** [comment]
Ok this puppeteer setup is working on both gitpod (for manual tests) and github action (for CI)
next steps : 
* download and boot a server using minecraft wrap (see mineflayer tests for example)
* run prismarine-viewer on it
* check the console has no error (both node and browser)
* take a screenshot and upload it as github action artifact

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/test/common/parallel.js this (make it a bit more github action native maybe)
+ something like this https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/test/clientTest.js#L16

(another example there https://github.com/PrismarineJS/node-minecraft-wrap/blob/master/test/wrap_server.js )

**Comment by rom1504** [comment]
it works, we now have screenshots automatically generated in a few minutes for all versions supported by mineflayer.
A few examples : 
1.8
test_1 8 8

1.11
test_1 11 2


1.16
test_1 16 1

**Comment by rom1504** [comment]
you can get the artifacts yourself there https://github.com/PrismarineJS/prismarine-viewer/suites/926021306/artifacts/11350390

**Comment by rom1504** [comment]
these images are now also auto pushed to https://github.com/PrismarineJS/prismarine-viewer/tree/gh-pages

will soon be in a website

**Comment by rom1504** [comment]
https://prismarine.js.org/prismarine-viewer/

**Comment by Karang** [comment]
nice

**Pull request merged**
