### PR TITLE
Support 1.18

### PR DESCRIPTION
**Pull request by rom1504**

### CODE REVIEW

**Comment by rom1504** [comment]
Ah we don't have Minecraft assets....

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/minecraft-assets/pull/14 need to do the same as this for 1.18.1

**Comment by dumbasPL** [comment]
> [PrismarineJS/minecraft-assets#14](https://github.com/PrismarineJS/minecraft-assets/pull/14) need to do the same as this for 1.18.1

https://github.com/PrismarineJS/minecraft-assets/pull/17

**Comment by rom1504** [comment]
test_1 18 1

looks like something is still missing

**Comment by rom1504** [comment]
test_1 18 1_2

not quite, need updated tint.json ...

**Comment by rom1504** [comment]
or actually is that right?

**Comment by rom1504** [comment]
yeah go

**Pull request merged**
